import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import test from 'node:test';
import { promisify } from 'node:util';

import { renderJenkinsfile, validatePipeline } from '../src/index.mjs';

const exec = promisify(execFile);

test('renders a deterministic declarative Jenkins pipeline', () => {
  const output = renderJenkinsfile({
    agent: 'any',
    stages: [{ name: 'Test', steps: ['npm test'] }],
  });
  assert.match(output, /^\/\/ Generated by/);
  assert.match(output, /pipeline \{/);
  assert.match(output, /stage\('Test'\)/);
  assert.match(output, /script: 'npm test'/);
  assert.equal(output, renderJenkinsfile({
    agent: 'any',
    stages: [{ name: 'Test', steps: ['npm test'] }],
  }));
});

test('escapes Groovy strings rather than creating new statements', () => {
  const output = renderJenkinsfile({
    agent: 'none',
    stages: [{ name: "Owner's check", steps: ["printf '%s\\n' safe"] }],
  });
  assert.match(output, /Owner\\'s check/);
  assert.match(output, /printf \\'%s\\\\n\\' safe/);
  assert.equal(output.split('\n').filter((line) => line.trimStart().startsWith('sh(')).length, 1);
});

test('rejects ambiguous or unbounded contracts', () => {
  assert.throws(() => validatePipeline({ agent: 'docker', stages: [] }), /agent/);
  assert.throws(
    () => validatePipeline({
      agent: 'any',
      stages: [
        { name: 'Same', steps: ['true'] },
        { name: 'Same', steps: ['true'] },
      ],
    }),
    /unique/,
  );
});

test('the CLI renders the committed consumer example', async () => {
  const { stdout, stderr } = await exec(
    process.execPath,
    ['bin/dankins.mjs', 'examples/pipeline.json'],
    { cwd: new URL('..', import.meta.url) },
  );
  assert.equal(stderr, '');
  assert.match(stdout, /stage\('Validate'\)/);
  assert.match(stdout, /npm pack --dry-run --json/);
});
