const MAX_STAGES = 64;
const MAX_STEPS = 64;
const MAX_STEP_LENGTH = 4_096;
const NAME = /^[A-Za-z0-9][A-Za-z0-9 '._/-]{0,79}$/;

function assertPlainObject(value, label) {
  if (!value || Array.isArray(value) || typeof value !== 'object') {
    throw new TypeError(`${label} must be an object`);
  }
}

function quoteGroovy(value) {
  return `'${value
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n')}'`;
}

export function validatePipeline(spec) {
  assertPlainObject(spec, 'pipeline');
  if (!['any', 'none'].includes(spec.agent)) {
    throw new TypeError('pipeline.agent must be exactly any or none');
  }
  if (!Array.isArray(spec.stages) || spec.stages.length === 0 || spec.stages.length > MAX_STAGES) {
    throw new TypeError(`pipeline.stages must contain 1-${MAX_STAGES} stages`);
  }

  const names = new Set();
  const stages = spec.stages.map((stage, stageIndex) => {
    assertPlainObject(stage, `stage ${stageIndex + 1}`);
    if (typeof stage.name !== 'string' || !NAME.test(stage.name)) {
      throw new TypeError(`stage ${stageIndex + 1} has an invalid name`);
    }
    if (names.has(stage.name)) {
      throw new TypeError(`stage names must be unique: ${stage.name}`);
    }
    names.add(stage.name);
    if (!Array.isArray(stage.steps) || stage.steps.length === 0 || stage.steps.length > MAX_STEPS) {
      throw new TypeError(`stage ${stage.name} must contain 1-${MAX_STEPS} steps`);
    }
    const steps = stage.steps.map((step, stepIndex) => {
      if (typeof step !== 'string' || step.length === 0 || step.length > MAX_STEP_LENGTH) {
        throw new TypeError(`stage ${stage.name} step ${stepIndex + 1} is invalid`);
      }
      if (step.includes('\0')) {
        throw new TypeError(`stage ${stage.name} step ${stepIndex + 1} contains NUL`);
      }
      return step;
    });
    return Object.freeze({ name: stage.name, steps: Object.freeze(steps) });
  });

  return Object.freeze({ agent: spec.agent, stages: Object.freeze(stages) });
}

export function renderJenkinsfile(input) {
  const pipeline = validatePipeline(input);
  const lines = [
    '// Generated by @oresoftware/dankins; edit the JSON contract, not this output.',
    'pipeline {',
    `  agent ${pipeline.agent}`,
    '  options {',
    '    disableConcurrentBuilds()',
    '    timestamps()',
    '  }',
    '  stages {',
  ];
  for (const stage of pipeline.stages) {
    lines.push(`    stage(${quoteGroovy(stage.name)}) {`, '      steps {');
    for (const [index, step] of stage.steps.entries()) {
      lines.push(
        `        sh(label: ${quoteGroovy(`step ${index + 1}`)}, script: ${quoteGroovy(step)})`,
      );
    }
    lines.push('      }', '    }');
  }
  lines.push('  }', '}', '');
  return lines.join('\n');
}
